### ISSUE TITLE
Changing to a region without data doesn't clean the graphics

### ISSUE THREAD

**Issue by svavassori** [fidash/widget-resourcesusage#14]
A clean of the graphics should be done when changing the Region instead of while receiving the data, otherwise old data are displayed.
If No data are received after a timeout, an error should be displayed

E.g. SophiaAntipolis -> Budapest

**Comment by bgrana** [comment]
Regions are now obtained directly through the monitoring API, so all regions have data. Were a region not to have any data, interface would clean all previous data.
